version: "3.9"
services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - fake_trade_bridge
    depends_on:
      - react-app
  react-app:
    build:
      context: ./react_app
      dockerfile: ./Dockerfile
    volumes:
      - ./react_app/src:/user/src/react_app/src
    container_name: react-app
    networks:
      fake_trade_bridge:
        aliases:
          - react-app
  flask-auth:
    build:
      context: ./flask_api
      dockerfile: Dockerfile
    container_name: flask-auth
    environment:
      FLASK_APP: "/var/www/flask_api/create_app.py"
      FLASK_ENV: "development"
      FAKETRADE_MONGO_STRING: "mongodb://mongo:27017/fakeTrade"
    volumes:
      - "./:/var/www:rw"
    networks:
      fake_trade_bridge:
        aliases:
          - flask-app
  flask-resource:
    build:
      context: ./flask_resource_api
      dockerfile: Dockerfile
    container_name: flask-resource
    environment:
      FLASK_APP: "/var/www/flask_resource_api/create_app.py"
      FLASK_ENV: "development"
      FAKETRADE_MONGO_STRING: "mongodb://mongo:27017/fakeTrade"
    volumes:
      - "./:/var/www:rw"
    networks:
      fake_trade_bridge:
        aliases:
          - flask-resource-app
  mongo-auth:
    image: mongo
    networks:
      - fake_trade_bridge
  mongo-resource:
    image: mongo
    networks:
      - fake_trade_bridge
networks:
  fake_trade_bridge: